version: '3'

services:
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    # Подключим локальную папку app как каталог /app в контейнере
    volumes:
      - ./app:/app
    # Опции нужы для того, чтобы контейнер не завершился сразу после запуска
    # То есть мы сможем подключиться к нему и работать в его консоле
    stdin_open: true
    tty: true
  tarantool:
    build: ./images/tarantool
    stdin_open: true
    tty: true
    ports:
      - "3301:3301"
    volumes:
      - ./app/data:/var/lib/tarantool
  admin:
    restart: always
    build: ./admin
    ports:
      - "8000:80"
    volumes:
      - ./admin/php:/var/www/html/php
      - ./admin/public/admin/js:/var/www/html/admin/js
      - ./admin/public/admin/index.php:/var/www/html/admin/index.php
      - ./admin/public/admin/style.css:/var/www/html/admin/style.css